PrimerBlog/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

	(r'^articulos/', include('blog.urls')),
    # Examples:
    # url(r'^$', 'PrimerBlog.views.home', name='home'),
    # url(r'^PrimerBlog/', include('PrimerBlog.foo.urls')),
    url(r'^$', 'blog.views.home', name='home'),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'^crear/', 'blog.views.crear', name='crear'),
)

blog/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
	url(r'^todos/$', 'blog.views.articulos'),
	url(r'^obtener/(?P<articulo_id>\d+)/$', 'blog.views.articulo'),
	url(r'^agregar_comentario/(?P<articulo_id>\d+)/$', 'blog.views.agregar_comentario'),
)

blog/models.py
from django.db import models

class Articulo(models.Model):
   autor = models.CharField(max_length = 30)
   titulo = models.CharField(max_length = 100)
   texto = models.TextField()
   fecha = models.DateTimeField()

class Comentario(models.Model):
   nombre = models.CharField(max_length = 200)
   cuerpo = models.TextField()
   fecha_pub = models.DateTimeField('fecha publicacion')
   articulo = models.ForeignKey(Articulo)

blog/forms.py
from django import forms
from models import Articulo, Comentario

from django.utils import timezone   


class ArticuloForm(forms.ModelForm):

   class Meta:
      model = Articulo

   #Validamos que el autor no sea menor a 3 caracteres
   def clean_autor(self):
      diccionario_limpio = self.cleaned_data
      
      autor = diccionario_limpio.get('autor')

      if len(autor) < 3:
         raise forms.ValidationError("El autor debe contener mas de tres caracteres")

      return autor	 

   #Validamos que el titulo no sea mayor a 50 caracteres
   def clean_titulo(self):
      diccionario_limpio = self.cleaned_data
      
      titulo = diccionario_limpio.get('titulo')

      if len(titulo) > 50:
         raise forms.ValidationError("El titulo debe ser menor a 50 caracteres")

      return titulo	

   #Validamos que el texto no sea mayor a 400 caracteres
   def clean_texto(self):
      diccionario_limpio = self.cleaned_data
      
      texto = diccionario_limpio.get('texto')

      if len(texto) > 400:
         raise forms.ValidationError("El texto no debe estar vacio")

      return texto	 

   #Validamos que la fecha no sea mayor a la fecha actual
   def clean_fecha(self):
      diccionario_limpio = self.cleaned_data
      
      fecha_articulo = diccionario_limpio.get('fecha')

      #Obtenemos la fecha actual
      fecha_actual = timezone.now()

      if fecha_actual < fecha_articulo:
         raise forms.ValidationError("El fecha no debe ser mayor al dia de hoy")

      return fecha_articulo


class ComentarioForm(forms.ModelForm):

   class Meta:
      model = Comentario
      fields = ('nombre', 'cuerpo')
      

blog/views.py
from django.shortcuts import render_to_response
from blog.models import Articulo, Comentario
from forms import ArticuloForm, ComentarioForm
from django.http import HttpResponseRedirect
from django.core.context_processors import csrf
from django.utils import timezone



def home(request):
   entradas = Articulo.objects.all()[:10]
   return render_to_response('index.html', {'articulos' : entradas})

def crear(request):
    if request.POST:
    	form = ArticuloForm(request.POST)
       	if form.is_valid():
       		form.save()

          	return HttpResponseRedirect('/')
    else:
       	form = ArticuloForm()
     
    args = {}
    args.update(csrf(request))
    
    args['form'] = form

    return render_to_response('crear_articulo.html', args)

def articulos(request):
  return render_to_response('index.html', {'articulos' : Articulo.objects.all() })

def articulo(request, articulo_id=1):
  return render_to_response('articulo.html', {'articulo' : Articulo.objects.get(id=articulo_id) })

def agregar_comentario(request, articulo_id):
    articulo = Articulo.objects.get(id=articulo_id)

    if request.POST:
      form = ComentarioForm(request.POST)
      if form.is_valid():
        comentario = form.save(commit=False)

        comentario.fecha_pub = timezone.now()
        comentario.articulo = articulo

        comentario.save()

        return HttpResponseRedirect('/articulos/obtener/%s' % articulo_id)
    else:
        form = ComentarioForm()
     
    args = {}
    args.update(csrf(request))
    
    args['articulo'] = articulo
    args['form'] = form

    return render_to_response('agregar_comentario.html', args)

blog/templates/agregar_comentario.html
<form action="/articulos/agregar_comentario/{{ articulo.id }}/" method="post">{% csrf_token %}
<ul>
{{ form.as_ul }}
</ul>

<input type="submit" name="submit" value="Agregar">
</form>

blog/templates/articulo.html
<!DOCTYPE html>
 
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>Mi primer Blog</title>
</head>
<body>

<div class="container">
    <h1>Mi primer blog</h1>
    <hr />
        <div class="art">
        <h2>{{ articulo.titulo }}</h2>
        <h3>Publicado el {{ articulo.fecha }} por {{ articulo.autor }}</h3>
        <p>{{ articulo.texto }}</p>
        </div>

<h2>Comentarios Disponibles</h2>
{% for c in articulo.comentario_set.all %}
	<p>{{ c.nombre}}: {{c.cuerpo}}</p>
{% endfor %}


<p><a href="/articulos/agregar_comentario/{{ articulo.id }}">Agregar Comentario</a></p>

</div>

</body>



</html>

blog/templates/crear_articulo.html
<form action="/crear/" method="post">{% csrf_token %}
<ul>
{{ form.as_ul }}
</ul>

<input type="submit" name="submit" value="Crear Articulo">
</form>

blog/templates/index.html
<!DOCTYPE html>
 
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>Mi primer Blog</title>
</head>
<body>

<div class="container">
    <h1>Mi primer blog</h1>
    <hr />
    {% for articulo in articulos %}
        <div class="art">
        <h2>{{ articulo.titulo }}</h2>
        <h3>Publicado el {{ articulo.fecha }} por {{ articulo.autor }}</h3>
        <p>{{ articulo.texto }}</p>
        </div>
        <hr />
    {% endfor %}
</div>

</body>
</html>